/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {
      colors: {
          "on-error-container": "#93000a",
          "surface-container-high": "#e4e9ed",
          "on-primary": "#ffffff",
          "inverse-on-surface": "#edf1f5",
          "background": "#f6fafe",
          "on-primary-fixed-variant": "#3f465c",
          "primary": "#000000",
          "primary-container": "#131b2e",
          "error": "#ba1a1a",
          "on-secondary-fixed-variant": "#304f00",
          "on-tertiary-fixed": "#410004",
          "tertiary-fixed": "#ffdad7",
          "on-background": "#171c1f",
          "surface-container-lowest": "#ffffff",
          "on-tertiary-fixed-variant": "#930014",
          "on-tertiary-container": "#f14143",
          "surface-bright": "#f6fafe",
          "on-secondary": "#ffffff",
          "outline": "#76777d",
          "surface-tint": "#565e74",
          "secondary-fixed-dim": "#91db2a",
          "on-surface-variant": "#45464d",
          "on-secondary-fixed": "#102000",
          "surface": "#f6fafe",
          "primary-fixed-dim": "#bec6e0",
          "secondary": "#416900",
          "tertiary-container": "#410004",
          "surface-dim": "#d6dade",
          "surface-container-low": "#f0f4f8",
          "error-container": "#ffdad6",
          "on-primary-container": "#7c839b",
          "inverse-surface": "#2c3134",
          "on-tertiary": "#ffffff",
          "tertiary": "#000000",
          "outline-variant": "#c6c6cd",
          "on-primary-fixed": "#131b2e",
          "on-secondary-container": "#457000",
          "inverse-primary": "#bec6e0",
          "surface-container-highest": "#dfe3e7",
          "secondary-fixed": "#acf847",
          "tertiary-fixed-dim": "#ffb3ae",
          "primary-fixed": "#dae2fd",
          "surface-container": "#eaeef2",
          "on-error": "#ffffff",
          "secondary-container": "#acf847",
          "on-surface": "#171c1f",
          "surface-variant": "#dfe3e7"
      },
      fontFamily: {
          "headline": ["Inter"],
          "body": ["Inter"],
          "label": ["Inter"]
      },
    },
  },
  plugins: [],
}
